version: '2.3'

services:
  helm-backend:
    container_name: helm-backend
    image: aymenkoched02/helm-backend:latest
    ports:
      - '7001:7001'

  helm-frontend:
    container_name: helm-frontend
    image: aymenkoched02/helm-frontend:latest
    ports:
      - '80:80'