version: '2.3'

services:
  helm-backend:
    container_name: helm-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '7001:7001'

  helm-frontend:
    container_name: helm-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.2
      args:
        - REACT_APP_BACKEND_HOST=localhost
        - REACT_APP_BACKEND_PORT=7001
    ports:
      - '80:80'