version: '2.3'

services:
  helm-backend:
    container_name: helm-backend
    image: aymenkoched02/backend-helm-image:latest
    ports:
      - '7001:7001'

  helm-frontend:
    container_name: helm-frontend
    image: aymenkoched02/frontend-helm-image:latest
    ports:
      - '80:80'