replicaCount: 3

backend:
  image:
    repository: "aymenkoched02/backend-helm-image"
    tag: "latest"
  containerPort: 7001
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  service:
    type: LoadBalancer
    port: 7001
    targetPort: 7001
    nodePort: 30001
  labels:
    app: backend
    tier: api
  podLabels:
    app: backend-pods
    tier: api

frontend:
  image:
    repository: "aymenkoched02/frontend-helm-image"
    tag: "latest"
  containerPort: 80
  env:
    REACT_APP_BACKEND_HOST: "localhost"
    REACT_APP_BACKEND_PORT: "7001"
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
    nodePort: 30002
  labels:
    app: frontend
    tier: web
  podLabels:
    app: frontend-pods
    tier: web