apiVersion: v1

kind: Service

metadata:
  name: backend-service
  labels:
    app: backend

spec:
  type: ClusterIP
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
  selector:
    app: backend-pods