name: Build and Push and Deploy Docker Images

on:
    push:
        branches:
            - master

jobs:
    backend:
        name: 'Build , Push & Deploy Backend'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build backend image
              run: |
                docker build -t aymenkoched02/backend-helm-image:latest ./backend

            - name: Push backend image
              run: |
                  docker push aymenkoched02/backend-image:latest