name: Build and Push Docker Images

on:
    push:
        branches:
            - master

jobs:
    filter:
        name: Filter Changed Paths
        runs-on: ubuntu-latest
        outputs:
            backend: ${{ steps.filter.outputs.backend }}
            frontend: ${{ steps.filter.outputs.frontend }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Filter changes
              id: filter
              uses: dorny/paths-filter@v2
              with:
                  filters: |
                    backend:
                        - 'backend/**'
                    frontend:
                        - 'frontend/**'

    backend:
        name: 'Build & Push Backend'
        runs-on: ubuntu-latest
        needs: filter
        if: ${{ needs.filter.outputs.backend == 'true' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build backend image
              run: |
                docker build -t aymenkoched02/backend-helm-image:latest ./backend

            - name: Push backend image
              run: |
                  docker push aymenkoched02/backend-helm-image:latest

    frontend:
        name: 'Build & Push Frontend'
        runs-on: ubuntu-latest
        needs: filter
        if: ${{ needs.filter.outputs.frontend == 'true' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build frontend image
              run: |
                  docker build -t aymenkoched02/frontend-helm-image:latest ./frontend

            - name: Push frontend image
              run: |
                  docker push aymenkoched02/frontend-helm-image:latest